# The camera intrinsic parameters matrix
# 3x3 matrix
camera_intrinsic_parameters: [241.4268236, 0,    376.0,
                              0,    241.4268236, 240.0,
                              0,    0,    1]

# Sampling time
dt: 0.025

# Gain on linear velocities
gain_v: 0.75

# Gain on angular velocities
gain_w: 1.1

# Threshold on the feature position error, used to stop the visual control
feature_error_threshold: 0.5
